### ISSUE TITLE
Getting 401 unauthorized (Invalid API key () specified.) for OauthsController when generating token and  allow_spree_api_key = false

### ISSUE THREAD

**Issue by zayter** [skukx/solidus_jwt#31]
issue happens because controller should skip load_user action the same as authenticate_user since that method tries to decode api_key  in  a open controller

the same applies when refreshing the token   

![image](https://user-images.githubusercontent.com/7431299/114326394-2fd63100-9afa-11eb-9c2a-2e4b223c9a2b.png)

the possible fix is adding this line :
![image](https://user-images.githubusercontent.com/7431299/114326728-bccdba00-9afb-11eb-87f3-e86b13025841.png)

I tested it manually and seems to be okay, will run the test but for sure there is an issue

if setting is set to true it works as expected

I can push a PR if needed

**Comment by skukx** [comment]
This is expected since there is no user to load in this controller. In order to obtain a token, then a username password or refresh token need to be sent in the request. Otherwise no token will be issued.

**Comment by zayter** [comment]
@skukx  username and password is sent, but since allow_spree_api_key is false the controller is returning 401 anyway because is needing a spree-api-key  that I do not want or need because I am using jwt and do not care about spree-api-key.


![image](https://user-images.githubusercontent.com/7431299/123714483-03e66400-d83c-11eb-91e3-64fcdb44da17.png)

**Comment by skukx** [comment]
I see,  I'll open a PR to test and fix this
